### ISSUE TITLE
Add a download button to `https://positron.posit.co/download`

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#5734]
We've got a very initial downloads page on our website here: https://positron.posit.co/download

We would like to add a button that helps folks download the correct version for them. Here are some examples:

- https://code.visualstudio.com/
- https://quarto.org/docs/get-started/
- https://posit.co/download/rstudio-desktop/

The logic that Quarto uses to create the button lives mainly in https://github.com/quarto-dev/quarto-web/blob/main/docs/download/_download.html. I will need a pointer to the logic for the RStudio webpage.

Some questions I have currently:

- Do we provide the system install for Windows users? What does VS Code do?
- Do we try this at all for Linux? Or just skip the button when Linux is the OS?
- What do we do on mobile? Both Quarto and RStudio give me the button for the macOS installer. 😆 I wonder what happens on Android?!

**Comment by juliasilge** [comment]
Another option to consider is to highlight the relevant row for a user.

**Comment by juliasilge** [comment]
If we do this:

```yaml
  navbar:
    left:
      - text: "Get Started"
        href: start.qmd
      - text: "Guides"
        href: add-to-path.qmd
      - text: "Help"
        href: troubleshooting.qmd
      - text: "<span class='btn btn-primary'>Download</span>"
        href: download.qmd

```

that gets us this:

![Image](https://github.com/user-attachments/assets/cb4c4339-b176-4454-9a49-eb0cad1ef9e1)

but we need to somehow get `vertical-align: middle` for those `nav-link` bits of text. I tried for a little while and didn't get very far.

It would be good to do this in general, because even on our [real site](https://positron.posit.co/) those links don't look great.
